services:
  - type: web
    name: flam-assignment
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
